PetNetApp/MVCPresentation/Models/FundraisingViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DataObjects;
using System.ComponentModel.DataAnnotations;

namespace MVCPresentation.Models
{
    public class CampaignsViewModel
    {
        public PagingInfo PagingInfo { get; private set; }
        [Display(Name = "Sort")]
        public SortingMethod? Sort { get; set; }
        [Display(Name = "Filter")]
        public FilterMethod? Filter { get; set; }
        public IEnumerable<FundraisingCampaignVM> Campaigns { get; set; }
        public IEnumerable<Shelter> Shelters { get; set; }
        public string Search { get; set; }
        public int? Shelter { get; set; }
        public CampaignsViewModel()
        {
            PagingInfo = new PagingInfo();
        }
    }
    public class FundraisingEventsViewModel
    {
        public PagingInfo PagingInfo { get; private set; }
        [Display(Name = "Sort")]
        public SortingMethod? Sort { get; set; }
        [Display(Name = "Filter")]
        public FilterMethod? Filter { get; set; }
        public IEnumerable<FundraisingEventVM> Events { get; set; }
        public IEnumerable<Shelter> Shelters { get; set; }
        public string Search { get; set; }
        public int? Shelter { get; set; }
        public FundraisingEventsViewModel()
        {
            PagingInfo = new PagingInfo();
        }
    }

    public class FundraisingCampaignForCampaignsModel
    {
        public FundraisingCampaignVM FundraisingCampaign { get; set; }
        public bool AlternateColor { get; set; }
    }

    public class FundraisingEventForEventsModel
    {
        public FundraisingEventVM FundraisingEvent { get; set; }
        public bool AlternateColor { get; set; }
    }

    public enum SortingMethod
    {
        [Display(Name = "Start Date")]
        StartDate,
        Title
    }
    public enum FilterMethod
    {
        Ongoing,
        Completed,
        Both
    }
}

PetNetApp/MVCPresentation/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCPresentation.Controllers
{
    public class EventsController : Controller
    {
        // GET: Events
        public ActionResult Index()
        {
            ViewBag.Tab = "Events";
            return View();
        }
    }
}

PetNetApp/MVCPresentation/Controllers/FundraisingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LogicLayer;
using LogicLayerInterfaces;
using DataObjects;
using MVCPresentation.Models;
using System.Threading.Tasks;

namespace MVCPresentation.Controllers
{
    public class FundraisingController : Controller
    {
        private MasterManager _masterManger = MasterManager.GetMasterManager();
        // GET: Fundraising
        public ActionResult Index()
        {
            @ViewBag.Tab = "Fundraising";
            return View();
        }

        /// <summary>
        /// Stephen Jaurigue
        /// Created: 2023/04/08
        /// 
        /// Controller method for /Fundraising/Campaign to view a single campaign
        /// </summary>
        /// <param name="campaign">the id of the campaign to view</param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> Campaign(int? campaign)
        {
            FundraisingCampaignVM fundraisingCampaign = null;
            try
            {

                if (campaign == null
                    || (fundraisingCampaign = _masterManger.FundraisingCampaignManager.RetrieveFundraisingCampaignByFundraisingCampaignId(campaign.Value)) == null
                    || !fundraisingCampaign.Active)
                {
                    return RedirectToAction("Campaigns");
                }
                fundraisingCampaign.Sponsors = _masterManger.InstitutionalEntityManager.RetrieveFundraisingSponsorsByCampaignId(campaign.Value);
                fundraisingCampaign.FundraisingEventList = _masterManger.FundraisingEventManager.RetrieveAllFundraisingEventsByCampaignId(campaign.Value).Cast<FundraisingEvent>().ToList();

                return View(fundraisingCampaign);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message + ex.InnerException.Message;
                return View("Error");
            }
        }

        /// <summary>
        /// Stephen Jaurigue
        /// Created: 2023/04/08
        /// 
        /// Controller method for /Fundraising/Campaign to get a partial view for a single campaign
        /// </summary>
        /// <param name="campaign">the id of the campaign to view</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Campaign(FormCollection collection)
        {
            int? campaign;
            try
            {
                campaign = Convert.ToInt32(collection.Get("campaign"));
            }
            catch
            {
                campaign = null;
            }
            FundraisingCampaignVM fundraisingCampaign = null;
            try
            {
                if (campaign == null
                    || (fundraisingCampaign = _masterManger.FundraisingCampaignManager.RetrieveFundraisingCampaignByFundraisingCampaignId(campaign.Value)) == null
                    || !fundraisingCampaign.Active)
                {
                    ViewBag.Message = "Could not find the selected campaign";
                    return PartialView("Error");
                }
                fundraisingCampaign.Sponsors = _masterManger.InstitutionalEntityManager.RetrieveFundraisingSponsorsByCampaignId(campaign.Value);
                fundraisingCampaign.FundraisingEventList = _masterManger.FundraisingEventManager.RetrieveAllFundraisingEventsByCampaignId(campaign.Value).Cast<FundraisingEvent>().ToList();

                return PartialView(fundraisingCampaign);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message + ex.InnerException.Message;

                return PartialView("Error");
            }
        }

        /// <summary>
        /// Stephen Jaurigue
        /// Created: 2023/04/08
        /// 
        /// Controller method for /Fundraising/Campaigns to view all public campaigns
        /// </summary>
        /// <param name="campaignsViewModel">The model holding the different parameters for searching and campaign data</param>
        /// <param name="Page">The current page were on</param>
        /// <returns></returns>
        public ActionResult Campaigns(CampaignsViewModel campaignsViewModel, int Page = 1)
        {
            @ViewBag.Tab = "Fundraising";
            PagingInfo pagingInfo = campaignsViewModel.PagingInfo;
            pagingInfo.CurrentPage = Page;
            pagingInfo.ItemsPerPage = 10;

            List<FundraisingCampaignVM> campaigns = null;
            try
            {
                
                campaignsViewModel.Shelters = _masterManger.ShelterManager.GetShelterList().Where(shelter => shelter.ShelterActive).OrderBy(sh => sh.ShelterName);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Error");
            }

            try
            {
                if (campaignsViewModel.Shelter != null)
                {
                    campaigns = _masterManger.FundraisingCampaignManager.RetrieveAllActiveFundraisingCampaignsByShelterId(campaignsViewModel.Shelter.Value);
                }
                else
                {
                    campaigns = _masterManger.FundraisingCampaignManager.RetrieveAllActiveFundraisingCampaigns();
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message + "\n\n" + ex.InnerException.Message;
                return View("Error");
            }

            Func<FundraisingCampaignVM, string> sortMethod = null;
            switch (campaignsViewModel.Sort)
            {
                case null:
                case SortingMethod.StartDate:
                    sortMethod = new Func<FundraisingCampaign, string>(fc => fc.StartDate != null ? fc.StartDate.Value.Ticks.ToString() : DateTime.MaxValue.Ticks.ToString());
                    break;
                case SortingMethod.Title:
                    sortMethod = new Func<FundraisingCampaign, string>(fc => fc.Title);
                    break;
            }

            Func<FundraisingCampaignVM, bool> filterMethod = null;
            switch (campaignsViewModel.Filter)
            {
                case null:
                case FilterMethod.Ongoing:
                    filterMethod = new Func<FundraisingCampaign, bool>(fc => !fc.Complete && fc.Active);
                    break;
                case FilterMethod.Completed:
                    filterMethod = new Func<FundraisingCampaign, bool>(fc => fc.Complete && fc.Active);
                    break;
                case FilterMethod.Both:
                    filterMethod = new Func<FundraisingCampaign, bool>(fc => fc.Active);
                    break;
            }

            Func<FundraisingCampaignVM, bool> searchForTextInFundraisingCampaign = (campaign) => true;

            if (campaignsViewModel.Search != null && campaignsViewModel.Search.Trim() != "")
            {
                campaignsViewModel.Search = campaignsViewModel.Search.Trim();
                searchForTextInFundraisingCampaign = (fundraisingCampaign) =>
                {
                    return fundraisingCampaign.Title?.IndexOf(campaignsViewModel.Search, StringComparison.OrdinalIgnoreCase) >= 0 ||
                            fundraisingCampaign.Description?.IndexOf(campaignsViewModel.Search, StringComparison.OrdinalIgnoreCase) >= 0 ||
                            (fundraisingCampaign.StartDate != null ? fundraisingCampaign.StartDate.Value.ToString("MM/dd/yyyy").Contains(campaignsViewModel.Search) : false) ||
                            (fundraisingCampaign.EndDate != null ? fundraisingCampaign.EndDate.Value.ToString("MM/dd/yyyy").Contains(campaignsViewModel.Search) : false) ||
                            (fundraisingCampaign.StartDate != null ? fundraisingCampaign.StartDate.Value.ToString("M/d/yyyy").Contains(campaignsViewModel.Search) : false) ||
                            (fundraisingCampaign.EndDate != null ? fundraisingCampaign.EndDate.Value.ToString("M/d/yyyy").Contains(campaignsViewModel.Search) : false);
                };
            }


            campaigns = campaigns.OrderBy(sortMethod).Where(filterMethod).Where(searchForTextInFundraisingCampaign).ToList();
            pagingInfo.TotalItems = campaigns.Count;

            if (pagingInfo.CurrentPage > pagingInfo.TotalPages)
            {
                pagingInfo.CurrentPage = pagingInfo.TotalPages;
            }
            if (pagingInfo.CurrentPage < 1)
            {
                pagingInfo.CurrentPage = 1;
            }

            campaignsViewModel.Campaigns = campaigns.Skip(pagingInfo.ItemsPerPage * (pagingInfo.CurrentPage - 1)).Take(pagingInfo.ItemsPerPage);
            return View(campaignsViewModel);
        }

        /// <summary>
        /// Barry Mikulas
        /// Created 04/18/2023
        /// 
        /// Controller method for \Fundraising\event to view a single event
        /// </summary>
        /// <remarks>
        /// Zaid Rachman
        /// 2023/04/26
        /// 
        /// Final QA
        /// </remarks>
        /// <param name="frEvent">the id of the event to view</param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> Event(int? frEvent)
        {
            FundraisingEventVM fundraisingEvent = null;
            try
            {

                if (frEvent == null
                    || (fundraisingEvent = _masterManger.FundraisingEventManager.RetrieveFundraisingEventByFundraisingEventId(frEvent.Value)) == null
                    || fundraisingEvent.Hidden)
                {
                    return RedirectToAction("Events");
                }
                fundraisingEvent.Sponsors = _masterManger.InstitutionalEntityManager.RetrieveFundraisingInstitutionalEntitiesByEventIdAndContactType(frEvent.Value, "Sponsor");

PetNetApp/MVCPresentation/Controllers/PledgeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LogicLayer;
using DataObjects;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace MVCPresentation.Controllers
{
    /// <summary>
    /// William Rients
    /// Created: 2023/04/20
    /// 
    /// Pledge controller
    /// </summary>
    public class PledgeController : Controller
    {
        private MasterManager masterManager = MasterManager.GetMasterManager();
        private ApplicationUserManager applicationUserManager;
        private PledgeVM pledgeVM;

        // GET: Pledge
        public ActionResult Index()
        {
            return View();
        }

        // GET: Pledge/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        /// <summary>
        /// William Rients
        /// Created: 2023/04/20
        /// 
        /// Get method for create pledge page
        /// 
        /// </summary>
        /// <returns></returns>
        // GET: Pledge/Create
        public ActionResult Create(int? fundrasingEventId)
        {
            ViewBag.Tab = "Fundraising";
            if (fundrasingEventId == null)
            {
                ViewBag.Message = "You must have an Event Id to create a pledge";

                return View("Error");
            }

            ViewBag.FundrasingEventId = fundrasingEventId;

            if (Session["pledgeStatus"] != null)
            {
                ViewBag.PledgeStatus = Session["pledgeStatus"].ToString();
                Session["pledgeStatus"] = null;
            }
            return View();
        }

        /// <summary>
        /// William Rients
        /// Created: 2023/04/19
        /// 
        /// Post method for creating a pledge, takes
        /// in a pledge Id
        /// 
        /// </summary>
        /// <param name="fundrasingEventId"></param>
        /// <returns></returns>
        // POST: Pledge/Create
        [HttpPost]
        public ActionResult Create(PledgeVM pledgeVM)
        {
            applicationUserManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = applicationUserManager.FindById(User.Identity.GetUserId());

            if (ModelState.IsValid)
            {
                try
                {
                    if (user != null)
                    {
                        // user has an account
                        pledgeVM.UserId = (int)user.UsersId;
                        masterManager.PledgeManager.CreatePledge(pledgeVM);
                    }
                    else
                    {
                        // user doesn't have an account & ID is null
                        masterManager.PledgeManager.CreatePledge(pledgeVM);
                    }
                    

                    Session["pledgeStatus"] = "Your Pledge has been Created!";
                    return RedirectToAction("Create");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.Message;

                    return View("Error");
                }
            }
            return View(pledgeVM);
        }
    }
}

PetNetApp/MVCPresentation/Views/Fundraising/Campaign.cshtml
@model DataObjects.FundraisingCampaignVM

@section styles
{
    <link href="~/Content/Fundraising/campaign-partial.css" rel="stylesheet" />
    <link href="~/Content/Fundraising/campaign.css" rel="stylesheet" />
}
@section scripts
{
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
}

<div class="campaign-container">
    <div class="campaign-main-grid">
        <h2 class="campaign-title">@Model.Title</h2>
        <div class="campaign-date-grid">
            <h3 class="campaign-start-date-label">Start Date:</h3>
            <h4 class="campaign-start-date">@(Model.StartDate.HasValue ? Model.StartDate.Value.ToString("MMMM d, yyyy") : "")</h4>
            <h3 class="campaign-end-date-label">End Date:</h3>
            <h4 class="campaign-end-date">@(Model.EndDate.HasValue ? Model.EndDate.Value.ToString("MMMM d, yyyy") : "")</h4>
        </div>
        <div class="campaign-description-group">
            <h3 class="campaign-description-label">Description</h3>
            <h5 class="campaign-description">@Model.Description</h5>
        </div>
        <div class="campaign-hosts-sponsors-events-results-grid">
            <div class="campaign-hosts-sponsors-group">
                <h3 class="campaign-entity-label">Hosts/Sponsors</h3>
                <div class="campaign-entities">
                    @if (Model.Sponsors.Count > 0)
                    {
                        foreach (var item in Model.Sponsors)
                        {
                            <h5 class="campaign-entity">@(item.GivenName + " " + item.FamilyName)</h5>
                        }
                    }
                    else
                    {
                        <h5 class="campaign-entity">None</h5>
                    }
                </div>
            </div>
            <div class="campaign-events-group">
                <h3 class="campaign-events-label">Events</h3>
                <div class="campaign-events">
                    @if (Model.FundraisingEventList.Count > 0)
                    {
                        foreach (var item in Model.FundraisingEventList)
                        {
                            <h5 class="campaign-event">@(item.Title)</h5>
                        }
                    }
                    else
                    {
                        <h5 class="campaign-event">None</h5>
                    }
                </div>
            </div>
            <div class="campaign-results-group">
                <h3 class="campaign-results-label">Results</h3>
                <div class="campaign-results">
                    <h4 class="campaign-amount-raised-label">Amount Raised:</h4>
                    <h5 class="campaign-amount-raised">$@Model.AmountRaised</h5>
                    <h4 class="campaign-event-count-label">Events:</h4>
                    <h5 class="campaign-event-count">@Model.FundraisingEventList.Count</h5>
                    <h4 class="campaign-adopted-count-label">Adopted:</h4>
                    <h5 class="campaign-adopted-count">@Model.NumAnimalsAdopted</h5>
                </div>
            </div>
        </div>
    </div>
</div>

PetNetApp/MVCPresentation/Views/Fundraising/Campaigns.Mobile.cshtml
@model MVCPresentation.Models.CampaignsViewModel

@{
    ViewBag.Title = "Campaigns";
}

@section styles
{
    @*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">*@
    <link href="~/Content/Fundraising/campaigns.css" rel="stylesheet" />
    <link href="~/Content/Fundraising/campaigns-mobile.css" rel="stylesheet" />
    <link href="~/Content/Fundraising/campaign-partial.css" rel="stylesheet" />
    <link href="~/Content/Fundraising/page-navigation.css" rel="stylesheet" />
    <link href="~/Content/button-styles.css" rel="stylesheet" />
}

@section scripts
{
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>*@
    <script src="~/Scripts/fundraising-campaigns.js"></script>
}

<div class="modal" tabindex="-1" role="dialog" id="campaignModal">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="modal-campaign">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="petnet-input modal-close-button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="campaigns-main-grid">
    <div class="campaigns-title-group">
        <h3 class="campaigns-title">Fundraising Campaigns</h3>
    </div>
    @using (Html.BeginForm("Campaigns", "Fundraising", FormMethod.Get, new { @class = "campaign-inputs" }))
    {
        @Html.AntiForgeryToken()
        <div class="search-group">
            @Html.TextBoxFor(model => model.Search, new { @class = "search-input petnet-input", placeholder = "Search" })
        </div>
        <div class="sort-button-group">
            <input type="button" class="sort-button default-button" data-toggle="modal" data-target="#filterModal" value="Filter" />
        </div>
        <!-- Modal -->
        <div class="modal fade filter-modal" id="filterModal" role="dialog" aria-labelledby="filterModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="filterModalLongTitle">Filter</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="shelter-group">
                            @{
                                SelectList list = new SelectList(Model.Shelters, "ShelterId", "ShelterName");
                            }
                            @Html.DropDownListFor(model => model.Shelter, list, "All Shelters", new { @class = "shelter-input petnet-input" })
                        </div>
                        <div class="sort-group">
                            @Html.EnumDropDownListFor(model => model.Sort, "Sort", new { @class = "sort-input petnet-input" })
                        </div>
                        <div class="filter-group">
                            @Html.EnumDropDownListFor(model => model.Filter, "Filter", new { @class = "filter-input petnet-input" })
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="filter-modal-close-group">
                            <input type="button" value="Close" data-dismiss="modal" class="modal-close-button modal-button petnet-input" />
                        </div>
                        <div class="search-button-group">
                            <input type="submit" value="Apply" class="modal-apply-button modal-button default-button" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
    <div class="campaigns-list @(Model.Campaigns.Count() == 0 ? "campaigns-list-empty" : "")">
        @{
            if (Model.Campaigns.Count() > 0)
            {
                bool alternate = false;
                foreach (var campaign in Model.Campaigns)
                {
                    @Html.Partial("FundraisingCampaignForCampaigns", new MVCPresentation.Models.FundraisingCampaignForCampaignsModel() { FundraisingCampaign = campaign, AlternateColor = alternate });
                    alternate = !alternate;
                }
            }
            else
            {
                <div class="no-campaigns-group">
                    <h4 class="no-campaigns-text">No fundraising campaigns found</h4>
                </div>
            }
        }
    </div>
    <div class="nav-buttons">
        <div class="nav-buttons-center">
            @Html.PageLinks(Model.PagingInfo, (page) => Url.Action("Campaigns",
                new { Sort = (int?)Model.Sort, Filter = (int?)Model.Filter, Search = Model.Search, Shelter = Model.Shelter, Page = page }))
        </div>
    </div>
</div>

PetNetApp/MVCPresentation/Views/Fundraising/FundraisingCampaignForCampaigns.cshtml
@model MVCPresentation.Models.FundraisingCampaignForCampaignsModel

<div class="@(!Model.AlternateColor ? "campaign-control-primary campaign-control" : "campaign-control-alternate campaign-control")">
    <div class="campaign-control-text-container">
        <p class="campaign-control-text">@Model.FundraisingCampaign.Title | @(Model.FundraisingCampaign.StartDate != null ? Model.FundraisingCampaign.StartDate.Value.ToString("MMMM d, yyyy") : "None")</p>
    </div>
    @using (Html.BeginForm("Campaign", "Fundraising", FormMethod.Get, new { @class = "campaign-control-button-group" }))
    {
        @Html.Hidden("campaign", Model.FundraisingCampaign.FundraisingCampaignId);
        <input type="submit" value="View" data-title="@Model.FundraisingCampaign.Title" data-id="@Model.FundraisingCampaign.FundraisingCampaignId" class="@("campaign-link " + (!Model.AlternateColor ? "campaign-link-primary" : "campaign-link-alternate"))"/>
    }
</div>

PetNetApp/MVCPresentation/Views/Fundraising/FundraisingEventForEvents.cshtml
@model MVCPresentation.Models.FundraisingEventForEventsModel


<div class="@(!Model.AlternateColor ? "event-control-primary event-control " : "event-control-alternate event-control")">
    <div class="event-control-text-container ">
        <p class="event-control-text text-truncate">@Model.FundraisingEvent.Title | @(Model.FundraisingEvent.StartTime != null ? Model.FundraisingEvent.StartTime.Value.ToString("MMMM d, yyyy") : "None")</p>
    </div>
    @using (Html.BeginForm("Create", "Pledge", FormMethod.Get, new { @class = "event-control-button-group2" }))
    {
        @Html.Hidden("fundrasingEventId", Model.FundraisingEvent.FundraisingEventId);
        <input type="submit" value="Pledge" data-title="@Model.FundraisingEvent.Title" data-id="@Model.FundraisingEvent.FundraisingEventId" class="@("pledge-link " + (!Model.AlternateColor ? "event-link-primary" : "event-link-alternate"))" />
    }
    @using (Html.BeginForm("Event", "Fundraising", FormMethod.Get, new { @class = "event-control-button-group" }))
    {
        @Html.Hidden("event", Model.FundraisingEvent.FundraisingEventId);
        <input type="submit" value="View" data-title="@Model.FundraisingEvent.Title" data-id="@Model.FundraisingEvent.FundraisingEventId" class="@("event-link " + (!Model.AlternateColor ? "event-link-primary" : "event-link-alternate"))" />
    }
</div>

PetNetApp/MVCPresentation/Views/Fundraising/Index.cshtml
@*@Html.Partial("_PartialFundraisingSubMenu")*@

@{
    ViewBag.Title = "Fundraising";
}