PetNetApp/MVCPresentation/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataObjects;
using LogicLayerInterfaces;
using LogicLayer;
using MVCPresentation.Models;
using System.Drawing;
using System.Threading.Tasks;
using static DataObjects.SurrenderForm;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace MVCPresentation.Controllers
{
    public class AnimalsController : Controller
    {
        private MasterManager _manager = null;
        private Animal _animal = null;
        private ApplicationUserManager userManager;




        public AnimalsController(MasterManager manager)     
        {
            _manager = manager;
            //_animal = animal;
        }

        public AnimalsController()
        {
            _manager = MasterManager.GetMasterManager();
        }

        public ActionResult Index()
        {
            ViewBag.Tab = "Adopt";
            return View();
        }

        // GET: Animals
        public ActionResult AdoptionApplication(int animalId, Users user)
        {
            try
            {
                ViewBag.HomeTypes = _manager.AdoptionApplicationManager.RetrieveAllHomeTypes();
                ViewBag.HomeOwnershipTypes = _manager.AdoptionApplicationManager.RetrieveAllHomeOwnershipTypes();
                ViewBag.AnimalId = animalId.ToString();
                ViewBag.AnimalName = _manager.AnimalManager.RetrieveAnimalAdoptableProfile((int)animalId).AnimalName;
                if(user != null)
                {
                    ViewBag.UserId = user.UsersId;
                }
                
                // pass user to view in a hidden field

            }
            catch (Exception up)
            {
                ViewBag.Message = up.InnerException.Message;
                return View("Error");
            }
            return View();
        }

        [HttpPost]
        public ActionResult AdoptionApplication(AdoptionApplicationVM _application)
        {
            ViewBag.Tab = "Adopt";

            if (!ModelState.IsValid)
            {
                return View(_application);
            }
            else
            {
                try
                {
                    Applicant applicant = new Applicant()
                    {
                        ApplicantGivenName = _application.AdoptionApplicant.ApplicantGivenName,
                        ApplicantFamilyName = _application.AdoptionApplicant.ApplicantFamilyName,
                        ApplicantAddress = _application.AdoptionApplicant.ApplicantAddress,
                        ApplicantAddress2 = _application.AdoptionApplicant.ApplicantAddress2 == null ? "" : _application.AdoptionApplicant.ApplicantAddress2,
                        ApplicantZipCode = _application.AdoptionApplicant.ApplicantZipCode,
                        ApplicantPhoneNumber = _application.AdoptionApplicant.ApplicantPhoneNumber,
                        ApplicantEmail = _application.AdoptionApplicant.ApplicantEmail,
                        HomeTypeId = _application.AdoptionApplicant.HomeTypeId,
                        HomeOwnershipId = _application.AdoptionApplicant.HomeOwnershipId,
                        NumberOfChildren = _application.AdoptionApplicant.NumberOfChildren,
                        NumberOfPets = _application.AdoptionApplicant.NumberOfPets
                    };

                    userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    var user = userManager.FindById(User.Identity.GetUserId());
                    if(user != null)
                    {
                        applicant.UserId = user.UsersId;
                    }

                    //AnimalVM animal = _manager.AnimalManager.RetriveAnimalAdoptableProfile(_application.AnimalId);

                    AdoptionApplicationVM application = new AdoptionApplicationVM()
                    {
                        AdoptionApplicant = applicant,
                        AdoptionApplicationDate = DateTime.Now,
                        AnimalId = _application.AnimalId
                        //AdoptionAnimal = animal
                    };
                    
                    _manager.AdoptionApplicationManager.AddAdoptionApplication(application);

                }
                catch (Exception up)
                {
                    ViewBag.Message = up.InnerException.Message;
                    return View("Error");
                }
            }
            ViewBag.Message = "Your application has been submitted!";
            return View("Success");
            
        }


        /// <summary>
        /// Andrew Schneider
        /// Created: 2023/04/19
        /// 
        /// Controller method for /Animals/Adoptable to view a list of adoptable animals
        /// </summary>
        /// 
        /// <remarks>
        /// Andrew Cromwell
        /// Updated 2023/04/20
        /// 
        /// Added the Viewbag.DisplayedAnimals and FilterOptions to allow for filtering by animal type
        /// </remarks>
        /// <returns>Adoptable View</returns>
        [HttpGet]
        public ActionResult Adoptable()
        {
            ViewBag.Tab = "Adopt";

            List<AdoptableAnimalModel> adoptableAnimalModels = new List<AdoptableAnimalModel>();
            List<AnimalVM> animalVMs = new List<AnimalVM>();
            try
            {
                animalVMs = _manager.AnimalManager.RetrieveAllAdoptableAnimals();
                ViewBag.DisplayedAnimals = "All Animals";
                List<string> filterOptions = new List<string>()
                {
                    "All",
                    "Cats",
                    "Dogs",
                    "Birds",
                    "Other"
                };
                ViewBag.FilterOptions = filterOptions;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View("Error");
            }

            foreach (var animal in animalVMs)
            {
                AdoptableAnimalModel adoptableAnimalModel = new AdoptableAnimalModel();
                adoptableAnimalModel.AnimalVM = animal;
                List<Images> imagesList = new List<Images>();
                try
                {
                    imagesList = _manager.ImagesManager.RetrieveAnimalImagesByAnimalId(animal.AnimalId);
                    adoptableAnimalModel.AnimalImageSource = "/Images/Animal/no_image.png";
                }
                catch
                {
                    adoptableAnimalModel.AnimalImageSource = "/Images/Animal/no_image.png";
                }

                try
                {
                    adoptableAnimalModel.ShelterName = " | " + _manager.ShelterManager.
                        RetrieveShelterVMByShelterID(animal.AnimalShelterId).ShelterName;
                }
                catch
                {
                    adoptableAnimalModel.ShelterName = "";
                }
                adoptableAnimalModels.Add(adoptableAnimalModel);
            }
            return View(adoptableAnimalModels);
        }

        /// <summary>
        /// Andrew Cromwell
        /// Created: 2023/04/21
        /// 
        /// Displays the animals of the type selected by the user.
        /// </summary>
        /// <remarks>
        /// Zaid Rachman
        /// Updated: 2023/04/21
        /// Final QA
        /// </remarks>
        /// <returns></returns>
        [HttpPost, ActionName("Adoptable")]
        public ActionResult FilterAdoptable()
        {
            ViewBag.Tab = "Adopt";
            string filterFromForm = Convert.ToString(Request["FilterAnimal"].ToString());
            List<AdoptableAnimalModel> adoptableAnimalModels = new List<AdoptableAnimalModel>();
            List<AnimalVM> animalVMs = new List<AnimalVM>();
            try
            {
                switch (filterFromForm)
                {
                    case "All":
                        animalVMs = _manager.AnimalManager.RetrieveAllAdoptableAnimals();
                        ViewBag.DisplayedAnimals = "All Animals";
                        break;
                    case "Dogs":
                        animalVMs = _manager.AnimalManager.RetrieveAllAdoptableAnimals().Where(A => A.AnimalTypeId == "Dog").ToList();
                        ViewBag.DisplayedAnimals = "Dogs";
                        break;
                    case "Cats":
                        animalVMs = _manager.AnimalManager.RetrieveAllAdoptableAnimals().Where(A => A.AnimalTypeId == "Cat").ToList();
                        ViewBag.DisplayedAnimals = "Cats";
                        break;
                    case "Birds":
                        animalVMs = _manager.AnimalManager.RetrieveAllAdoptableAnimals().Where(A => A.AnimalTypeId == "Bird").ToList();
                        ViewBag.DisplayedAnimals = "Birds";
                        break;
                    case "Other":
                        animalVMs = _manager.AnimalManager.RetrieveAllAdoptableAnimals().Where(A => A.AnimalTypeId != "Dog" && A.AnimalTypeId != "Cat" &&
                            A.AnimalTypeId != "Bird").ToList();
                        ViewBag.DisplayedAnimals = "Other Animals";
                        break;
                    default:
                        break;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View("Error");
            }
            List<string> filterOptions = new List<string>()
                {
                    "All",
                    "Cats",
                    "Dogs",
                    "Birds",
                    "Other"
                };
            ViewBag.FilterOptions = filterOptions;
            foreach (var animal in animalVMs)
            {

PetNetApp/MVCPresentation/Controllers/UserProfileController.cs
using DataObjects;
using LogicLayer;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using MVCPresentation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCPresentation.Controllers
{
    /// <summary>
    /// Chris Dreismeier
    /// Created: 2023/04/27
    /// 
    /// User Profile Controller
    /// </summary>
    public class UserProfileController : Controller
    {
        MasterManager _manager = MasterManager.GetMasterManager();

        /// <summary>
        /// Chris Dreismeier
        /// Created: 2023/04/27
        /// 
        /// Displays the users profile and the users information
        /// </summary>
        // GET: UserProfile
        [Authorize]
        public ActionResult Index()
        {
            var dbContext = new ApplicationDbContext();
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(dbContext));
            var user = userManager.FindById(User.Identity.GetUserId());

            try
            {
                if(user.ShelterId != null)
                {
                    var userShelter = _manager.ShelterManager.RetrieveShelterVMByShelterID((int)user.ShelterId);
                    ViewBag.UserShelterName = userShelter.ShelterName;
                }
                else
                {
                    ViewBag.NoShelter = "You do not have a shelter selected!";
                }
                
            }
            catch (Exception ex)
            {

                throw;
            }
            return View(); 
        }

        // Code by Alexis Oetken 
        public ActionResult AddBookmark(int? animalID, Users user)
        {
            var bookmarkManager = new LogicLayer.BookmarkManager();
            if (ModelState.IsValid)
            {
                try
                {
                    ViewBag.User = user; 

                    if (animalID == null)
                    {
                        ViewBag.Message = "Something went wrong! Please try again.";
                        return View("Error");
                    }

                    if (user == null)
                    {
                        ViewBag.Message = "Please sign in to use this feature.";
                        return View("Error");
                    }

                    else
                    {
                        bookmarkManager.AddBookmark((int)user.UsersId, (int)animalID);
                        return RedirectToAction("Index");
                    }

                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.Message;
                    return View("Error");
                }
            }
            return View();
        }

        //Code by Alexis Oetken 
        public ActionResult DeleteBookmark(int? animalID, Users user)
        {
            try
            {
                var bookmarkManager = new LogicLayer.BookmarkManager();

            ViewBag.User = user;

            bookmarkManager.DeleteBookmark((int)user.UsersId, (int)animalID);
            return RedirectToAction("Index");
            }
            catch (Exception)
            {
                throw;
            }
            

        }

        // Code by Alexis Oetken 
        public ActionResult ViewAllBookmarks(int userID)
        {
            try
            {
                var bookmarkManager = new LogicLayer.BookmarkManager();

                List<DataObjects.Bookmark> bookmarkList = bookmarkManager.RetrieveAllBookmarks(userID);

                return View("BookmarksView", bookmarkList);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View("Error");
            }
        }

        /// <summary>
        /// Molly Meister
        /// Created: 2023/04/23
        /// 
        /// Displays the adoption applications for the user.
        /// <paramref name="userId"/>
        /// </summary>
        //GET: UserProfile/MyApplications/6
        [ChildActionOnly]
        public ActionResult AdoptionApplicationsPartial(int userId)
        {
            try
            {
                List<AdoptionApplicationVM> applications = _manager.AdoptionApplicationManager.RetrieveAllAdoptionApplicationsByUsersId(userId);
                return PartialView(applications);
            }
            catch (Exception up)
            {
                ViewBag.Message = up.Message;
                return View("Error");
                //return View("Error");
            }
        }
    }
}

PetNetApp/MVCPresentation/Views/UserProfile/AdoptionApplicationsPartial.cshtml
@model IEnumerable<DataObjects.AdoptionApplicationVM>

@if (Model.Any())
{
    <table class="table">
        @foreach (var item in Model)
        {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AdoptionAnimal.AnimalName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AdoptionAnimal.AnimalShelterId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicationStatusId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AdoptionApplicationDate)
                    </td>
                    @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.AdoptionApplicationId }) |
                        @Html.ActionLink("Details", "Details", new { id = item.AdoptionApplicationId }) |
                    </td>*@
                </tr>
        }

    </table>
}
else
{
    <h3>No Applications Available</h3>
}

PetNetApp/MVCPresentation/Views/UserProfile/BookmarksView.cshtml
@model IEnumerable<DataObjects.Bookmark>
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.Owin
    @{
        Layout = null;
    }

    @{
        ViewBag.Title = "BookmarksView";
    }

    <div>
        <br />
        <table class="table">

            @if (Model == null)
            {
               
            }
            else
            {
            foreach (var item in Model)
            {
                        @Html.DisplayFor(modelItem => item.AnimalName) <br />

                        @Html.ActionLink("Profile    ", "AdoptableAnimal", "Animals", new { animalId = item.AnimalId }, null) <br />

                        @Html.ActionLink("Delete", "DeleteBookmark", new { animalId = item.AnimalId })    <br /> <br />
            }
            }
        </table>
    </div>

PetNetApp/MVCPresentation/Views/UserProfile/Index.cshtml
@using System.Collections.Generic
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.Owin
@using DataObjects

@{
    ViewBag.Title = "Index";

}


@if (Request.IsAuthenticated)
{
    ApplicationUserManager userManager = Context.GetOwinContext().GetUserManager<ApplicationUserManager>();
    var user = userManager.FindById(User.Identity.GetUserId());

    <div class="container">
        <div class="row mb-4">
            <div class="col-md-3">
                <!-- Profile picture -->
                <img src="https://www.example.com/profile-pic.jpg" alt="Profile picture" class="img-fluid">
            </div>
            <div class="col-md-4">
                <!-- User information -->
                <div class="card ">
                    <div class="card-header">
                        User Information
                    </div>
                    <div class="card-body">
                        <!-- User information content -->
                        <div>
                            <div>
                                <h4>Name</h4>
                            </div>
                            <div>
                                <p class="card-text"> @user.GivenName @user.FamilyName</p>
                            </div>
                        </div>

                        <div>
                            <div>
                                <h4>UserID</h4>
                            </div>
                            <div>
                                <p class="card-text"> @user.UsersId</p>
                            </div>
                        </div>

                        <div>
                            <div>
                                <h4>UserName</h4>
                            </div>
                            <div>
                                <p class="card-text">@user.Email</p>
                            </div>
                        </div>

                        <div>
                            <div>
                                <h4>Email</h4>
                            </div>
                            <div>
                                <p class="card-text">@user.Email</p>
                            </div>
                        </div>

                        @*<div>
                            <div>
                                <h4>Address</h4>
                            </div>
                            <div>
                                <p class="card-text">@user.Address</p>
                            </div>
                        </div>*@
                        <div>
                            <div>
                                <h4>Your Shelter</h4>
                            </div>
                            <div>
                                <p class="card-text">@ViewBag.NoShelter</p>
                                <p class="card-text">@ViewBag.UserShelterName</p>
                            </div>
                        </div>


                        @if (user.AddressTwo != null)
                        {
                            <div>
                                <div>
                                    <h4>Adress two</h4>
                                </div>
                                <div>
                                    <p class="card-text">@user.AddressTwo</p>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div>
                    @Html.ActionLink("Manage Account", "UserDetails", "Manage", "", new { @class = "btn btn-primary btn-block m-3" })
                </div>
                <div>
                    @*<btn class="btn btn-primary btn-block m-3">Test</btn>*@
                    @Html.ActionLink("Change Your Shelter", "SelectShelter", "Shelters", "", new { @class = "btn btn-primary btn-block m-3" })
                </div>
                <div>
                    @*<btn class="btn btn-primary btn-block m-3">Test</btn>*@
                    @Html.ActionLink("View Your Donations", "Index", "UserDonations", "", new { @class = "btn btn-primary btn-block m-3" })
                </div>

            </div>
        </div>
        <div class="row">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link" id="application-tab" data-toggle="tab" href="#applications" role="tab" aria-controls="home"
                       aria-selected="false">My Applications</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile"
                       aria-selected="false">Bookmarks</a>
                </li>
                @*<li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact"
                       aria-selected="false">User Information</a>
                </li>*@
            </ul>
            <div class="tab-content container" id="myTabContent">
                <div class="tab-pane fade" id="applications" role="tabpanel" aria-labelledby="application-tab">
                    @Html.Action("AdoptionApplicationsPartial", "UserProfile", new { userId = user.UsersId })

                </div>
                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    @Html.Action("ViewAllBookmarks", "UserProfile", new { userID = user.UsersId })
                </div>
                @*<div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                    Etsy mixtape
                    wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack
                    lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard
                    locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify
                    squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie
                    etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog
                    stumptown. Pitchfork sustainable tofu synth chambray yr.
                </div>*@
            </div>
        </div>
    </div>



  }