PetNetApp/MVCPresentation/Models/DonationViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DataObjects;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

// Based on FundraisingViewModels.cs
namespace MVCPresentation.Models
{
    public class DonationsViewModel
    {
        public DonationSortOptions? Sort { get; set; }
        public MiscellaneousFilterOptions? MiscellaneousFilterOptions { get; set; }
        public AmountFilterOptions? AmountFilterOptions { get; set; }
        public DateFilterOptions? DateFilterOptions { get; set; }
        public IEnumerable<DonationVM> DonationVMs { get; set; }
        public IEnumerable<Shelter> Shelters { get; set; }
        public int? Shelter { get; set; }
        
        public int Count { get; set; }
    }

    public enum DonationSortOptions
    {
        [Display(Name = "Sort by Amount")]
        Amount,
        [Display(Name = "Sort by Date")]
        Date,
        [Display(Name = "Sort by Name")]
        FamilyName
    }


    public enum MiscellaneousFilterOptions
    {
        [Display(Name = "Has Message")]
        HasMessage,
        [Display(Name = "Has No Message")]
        HasNoMessage
    }

    public enum AmountFilterOptions
    {
        [Display(Name = "$1 to $25")]
        OneToTwentyFive,
        [Display(Name = "$26 to $50")]
        TwentyFiveToFifty,
        [Display(Name = "$51 to $100")]
        FiftyToOneHundred,
        [Display(Name = "$101 to $500")]
        OneHundredToFiveHundred,
        [Display(Name = "$501 or More")]
        OverFiveHundred
    }

    public enum DateFilterOptions
    {
        [Display(Name = "Last Day")]
        LastDay,
        [Display(Name = "Last Week")]
        LastWeek,
        [Display(Name = "Last Month")]
        LastMonth,
        [Display(Name = "Last 6 Months")]
        LastSixMonths,
        [Display(Name = "Last Year")]
        LastYear
    }
}

PetNetApp/MVCPresentation/Controllers/DonationsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using DataObjects;
using LogicLayer;
using MVCPresentation.Models;

namespace MVCPresentation.Controllers
{
    public class DonationsController : Controller
    {
        private MasterManager masterManager = MasterManager.GetMasterManager();
        private List<DonationVM> donationVMs;
        private DonationsViewModel _donationsViewModel = new DonationsViewModel();
        private DonationVM donationVM;
        private List<Shelter> _shelters;

        /// <summary>
        /// Author: Gwen Arman
        /// Date: 4/21/23
        /// </summary>
        /// 
        /// <remarks>
        /// Updater: Andrew Schneider
        /// Updated: 2023/04/26
        /// Added db calls and switch staments for the sort/filter functionality.
        /// 
        /// Zaid Rachman
        /// Updated: 2023/04/27
        /// Final QA
        /// </remarks>
        /// <param name="donationsViewModel">The view model that will be sorted, filtered, and displayed</param>
        /// <returns>Donations/Index view</returns>
        // GET: Donations
        public ActionResult Index(DonationsViewModel donationsViewModel)
        {
            ViewBag.Tab = "Donate";
            List<DonationVM> anonymousVMs = new List<DonationVM>();

            try
            {
                donationVMs = masterManager.DonationManager.RetrieveAllDonations();
            }
            catch (Exception)
            {
                ViewBag.Message = "Could not retrieve donations";
                View("Error");
            }

            try
            {
                _shelters = masterManager.ShelterManager.GetShelterList().
                    Where(shelter => shelter.ShelterActive).OrderBy(shelter => shelter.ShelterName).ToList();
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                View("Error");
            }

            try
            {
                if (donationsViewModel.Shelter != null)
                {
                    donationVMs = masterManager.DonationManager.RetrieveDonationsByShelterId(donationsViewModel.Shelter.Value);
                }
                else
                {
                    donationVMs = donationVMs = masterManager.DonationManager.RetrieveAllDonations();
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message + "\n\n" + ex.Message;
                return View("Error");
            }

            int dateRange = 0;

            switch (donationsViewModel.DateFilterOptions)
            {
                case null:
                    break;
                case DateFilterOptions.LastDay:
                    dateRange = 1;
                    break;
                case DateFilterOptions.LastWeek:
                    dateRange = 7;
                    break;
                case DateFilterOptions.LastMonth:
                    dateRange = 30;
                    break;
                case DateFilterOptions.LastSixMonths:
                    dateRange = 180;
                    break;
                case DateFilterOptions.LastYear:
                    dateRange = 365;
                    break;
            }
            
            if(dateRange != 0)
            {
                donationVMs = donationVMs.Where(d => d.DateDonated >= (DateTime.Today - TimeSpan.FromDays(dateRange))).ToList();
            }

            switch (donationsViewModel.AmountFilterOptions)
            {
                case null:
                    break;
                case AmountFilterOptions.OneToTwentyFive:
                    donationVMs = donationVMs.Where(d => d.Amount > 0 && d.Amount <= 25).ToList();
                    break;
                case AmountFilterOptions.TwentyFiveToFifty:
                    donationVMs = donationVMs.Where(d => d.Amount > 25 && d.Amount <= 50).ToList();
                    break;
                case AmountFilterOptions.FiftyToOneHundred:
                    donationVMs = donationVMs.Where(d => d.Amount > 50 && d.Amount <= 100).ToList();
                    break;
                case AmountFilterOptions.OneHundredToFiveHundred:
                    donationVMs = donationVMs.Where(d => d.Amount > 100 && d.Amount <= 500).ToList();
                    break;
                case AmountFilterOptions.OverFiveHundred:
                    donationVMs = donationVMs.Where(d => d.Amount > 500).ToList();
                    break;
            }

            switch (donationsViewModel.MiscellaneousFilterOptions)
            {
                case null:
                    break;
                case MiscellaneousFilterOptions.HasMessage:
                    donationVMs = donationVMs.Where(d => d.Message != null && d.Message != "").ToList();
                    break;
                case MiscellaneousFilterOptions.HasNoMessage:
                    donationVMs = donationVMs.Where(d => d.Message == null || d.Message == "").ToList();
                    break;
            }

            switch (donationsViewModel.Sort)
            {
                case null:
                case DonationSortOptions.Date:
                    donationVMs = donationVMs.OrderByDescending(d => d.DateDonated != null ?
                                    d.DateDonated.Value.Ticks.ToString() : DateTime.MaxValue.Ticks.ToString()).ToList();
                    break;
                case DonationSortOptions.FamilyName:
                    anonymousVMs = donationVMs.Where(d => d.Anonymous).ToList();
                    donationVMs = donationVMs.Where(d => !d.Anonymous).OrderBy(d => d.FamilyName).ToList();
                    donationVMs.AddRange(anonymousVMs);
                    break;
                case DonationSortOptions.Amount:
                    donationVMs = donationVMs.OrderBy(d => d.Amount == null ? 0 : d.Amount).ToList();
                    break;
            }

            donationsViewModel.Count = donationVMs.Count();
            donationsViewModel.DonationVMs = donationVMs;
            donationsViewModel.Shelters = _shelters;
            return View(donationsViewModel);
        }

        /// <summary>
        /// Author: Gwen Arman
        /// Date: 4/21/23
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Donations/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.Tab = "Donate";
            if (id != null)
            {
                try
                {
                    donationVM = masterManager.DonationManager.RetrieveDonationByDonationId(id.Value);
                }
                catch (Exception)
                {
                    ViewBag.Message = "Could not retrieve donation";
                    View("Error");
                }

                if (donationVM == null)
                {
                    ViewBag.Message = "No donation found";
                    return View("Error");
                } 
                else
                {
                    try
                    {
                        donationVM.InKindList = masterManager.DonationManager.RetrieveInKindsByDonationId(donationVM.DonationId);
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = ex.Message;
                        return View("Error");
                    }
                }

                return View(donationVM);
            }
            else
            {
                ViewBag.Message = "No donation with that ID";
                return View("Error");
            }
        }

        // GET: Donations/Filtered
        public ActionResult Filtered(DonationsViewModel donationsViewModel)
        {
            return View(donationsViewModel);
        }



        /// <summary>
        /// Author: Gwen Arman
        /// Date: 4/21/23
        /// </summary>
        /// <returns></returns>
        // GET: Donations/Create
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Author: Gwen Arman
        /// Date: 4/21/23
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        // POST: Donations/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PetNetApp/MVCPresentation/Views/Donations/Details.cshtml
@model DataObjects.DonationVM

@{
    ViewBag.Title = "Donation";
}

<h2>Donation</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            First Name
        </dt>
        @if (Model.Anonymous)
        {
            <dd>Anonymous</dd>
        }
        else if (Model.UserId == null)
        {
            <dd>
                @Html.DisplayFor(model => model.GivenName)
            </dd>
        }
        else
        {
            <dd>
                @Html.DisplayFor(model => model.User.GivenName)
            </dd>
        }

        <dt>
            Last Name
        </dt>
        @if (Model.Anonymous)
        {
            <dd>Anonymous</dd>
        }
        else if (Model.UserId == null)
        {
            <dd>
                @Html.DisplayFor(model => model.FamilyName)
            </dd>
        }
        else
        {
            <dd>
                @Html.DisplayFor(model => model.User.FamilyName)
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class="textWrap">
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            Date Donated
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateDonated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Target)
        </dt>
        <dd class="textWrap">
            @Html.DisplayFor(model => model.Target)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentMethod)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaymentMethod)
        </dd>
    </dl>
</div>
@if (Model.HasInKindDonation)
{
    <h4>In-Kind Donations</h4>
    <div class="container">
        <div class="row">
            <div class="col-xs-6">Description</div>
            <div class="col-xs-6">Quantity</div>
        </div>
        @foreach(var item in Model.InKindList)
        {
        <div class="row">
            <div class="col-xs-6">@item.Description</div>
            <div class="col-xs-6">@item.Quantity</div>
        </div>
        }
    </div>
}
<p>
    @Html.ActionLink("Back to Donations", "Index")
</p>

PetNetApp/MVCPresentation/Views/Donations/Index.cshtml
@model MVCPresentation.Models.DonationsViewModel

@{
    ViewBag.Title = "Donate";
}


<div class="container">
    <div class="row">
        <h2>Donations</h2>
    </div>

    <div class="row">
        <p>
            @Html.ActionLink("Donate Here!", "Donate","Donate", new { textarea = "" }, new { @class = "btn btn-primary" })
        </p>
        @using (Html.BeginForm("Index", "Donations", FormMethod.Get, new { @class = "ml-auto" }))
        {
            @Html.AntiForgeryToken()

            <div class="d-flex flex-row-reverse">
                <div class="p-1">
                    <input type="submit" value="Filter" class="btn btn-primary" tabindex="7"/>
                </div>
                <div class="p-1" tabindex="6">
                    @{
                        SelectList list = new SelectList(Model.Shelters, "ShelterId", "ShelterName");
                    }
                    @Html.DropDownListFor(model => model.Shelter, list, "All Shelters",
                            new { @class = "btn btn-secondary dropdown-toggle", @style = "background: #3d8361; border-color: #7fac92" })
                </div>

                <div class="p-1" tabindex="5">
                    @Html.EnumDropDownListFor(model => model.MiscellaneousFilterOptions, "Other Options",
                            new { @class = "btn btn-secondary dropdown-toggle", @style = "background: #3d8361; border-color: #7fac92" })
                </div>

                <div class="p-1" tabindex="4">
                    @Html.EnumDropDownListFor(model => model.AmountFilterOptions, "Amount",
                            new { @class = "btn btn-secondary dropdown-toggle", @style = "background: #3d8361; border-color: #7fac92" })
                </div>
                <div class="p-1" tabindex="3">
                    @Html.EnumDropDownListFor(model => model.DateFilterOptions, "Date", new
                    {
                        @class = "btn btn-secondary dropdown-toggle",
                   @style = "background: #3d8361; border-color: #7fac92"
                    })
                </div>
                <div class="p-1" tabindex="2">
                    @Html.EnumDropDownListFor(model => model.Sort, "Sort",
                            new { @class = "btn btn-secondary dropdown-toggle", @style = "background: #3d8361; border-color: #7fac92" })
                </div>
            </div>
        }

    </div>



    <div class="overflow">
        @if (Model.Count != 0)
        {
            <table class="table">
                <tr>
                    <th>
                        First Name
                    </th>
                    <th>
                        Last Name
                    </th>
                    <th>
                        Shelter Name
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Date
                    </th>
                    <th>
                        Message
                    </th>
                </tr>
                @foreach (var item in Model.DonationVMs)
                {
                    var date = item.DateDonated.Value.ToString("MM/dd/yyyy");
                    string shortMessage = "";
                    if (item.Message != null && item.Message.Length > 45)
                    {
                        shortMessage = item.Message.Substring(0, 45) + "...";
                    }
                    <tr>
                        @if (item.Anonymous)
                        {
                            <th>Anonymous</th>
                            <th></th>
                        }
                        else if (item.UserId == null)
                        {
                            <th>
                                @Html.DisplayFor(modelItem => item.GivenName)
                            </th>
                            <th>
                                @Html.DisplayFor(modelItem => item.FamilyName)
                            </th>
                        }
                        else
                        {
                            <th>
                                @Html.DisplayFor(modelItem => item.User.GivenName)
                            </th>
                            <th>
                                @Html.DisplayFor(modelItem => item.User.FamilyName)
                            </th>
                        }
                        <th>
                            @Html.DisplayFor(modelItem => item.ShelterName)
                        </th>
                        <th>
                            $@Html.DisplayFor(modelItem => item.Amount)
                        </th>
                        <th>
                            @Html.DisplayFor(modelItem => date)
                        </th>
                        @if (item.Message != null && item.Message.Length > 45)
                        {
                            <th>
                                @Html.DisplayFor(modelItem => shortMessage)
                            </th>
                        }
                        else
                        {
                            <th>
                                @Html.DisplayFor(modelItem => item.Message)
                            </th>
                        }
                        <td>
                            @Html.ActionLink("View", "Details", new { id = item.DonationId }, new { @class = "btn btn-primary" })
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p class="h2">No donations to display</p>
        }

    </div>
</div>